# =======================
# CONFIGURACIoN DE SPRING
# =======================

# Railway asigna un puerto automáticamente
server.port=${PORT:8080}

# =======================
# BASE DE DATOS Railway
# =======================
spring.datasource.url=mysql.railway.internal
spring.datasource.username=root
spring.datasource.password=YbCNcnrkjoJAggDQFfqQUlthRwUpAnrK

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.thymeleaf.cache=false

# =======================
# CONFIGURACIoN DE CORREO (GMAIL)
# =======================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=drues0221@gmail.com
spring.mail.password=jtaiwssmdugfyiod

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000
